name: fullstack

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - ./backend:/app
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    expose:
      - 3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
